spring:
  application:
    name: chatmodel-chatresponse-generation-sample
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
server:
  port: 9204
logging:
  level:
    org.springframework.ai: DEBUG
